name: End-to-end tests

on:
  push:
    branches:
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config-file: cypress.json
          spec: 'src/tests/e2e/**/*'
          browser: chrome
          headless: true
        env:
          CYPRESS_baseUrl: http://localhost:8080/
